rails/thor

- lib/thor/shell/basic.rb
- spec/shell/color_spec.rb
This fixes a problem using an array of colors or the
legacy color syntax with `ask` or any of the methods
that depend on it.
The symptom of the problem is that the color arg would
prefix the message:
[:green, :on_red, :bold]Not what you expected?
[:blue, false]Why isn't this blue?
> Fix for an array of colors with ask/yes?/no?

- lib/thor/parser/arguments.rb
- spec/parser/options_spec.rb
Just a small update to validate a user only enters a key for a hash option at most once. Issue #455
> Issue #455 - only allow a hash key to be specified once

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
__Example:__
```ruby
say "Hello!"
indent do
say "I'm indented 2 spaces!"
indent do
say "I'm indented 4 spaces!"
indent(2) { say "I'm indented 8 spaces!"  }
end
end
say "I'm not indented anymore!"
```
__Output:__
```
Hello!
I'm indented 2 spaces!
I'm indented 4 spaces!
I'm indented 8 spaces!
I'm not indented anymore!
```
> Add indent method to Thor::Shell::Basic

- lib/thor/parser/option.rb
- spec/parser/option_spec.rb
Do not generate a negative option (--no-no-foo) for already negative boolean options (--no-foo)
> Negative options

- lib/thor.rb
- lib/thor/base.rb
- lib/thor/command.rb
- spec/thor_spec.rb
This is added so the class options can be disabled for the help command. Fixes #363
> Add ability to disable class options for a command

- lib/thor/core_ext/hash_with_indifferent_access.rb
- spec/core_ext/hash_with_indifferent_access_spec.rb
options (HashWithIndifferentAccess) has key checkable by either strings or symbols
> Add key? method for improving ::Hash compatibility

- Gemfile
- lib/thor.rb
The values of a hash someplace were being obtained using a non-standard method, as if the hash was a 2D array. This has been replaced with the `.values` method now. Tests have been checked locally on Ruby version 2.2.3. They're passing. Travis will execute them on remaining environments.
> replaced '.map{|_,o| o}' on hash with '.values'

- Gemfile
Only to 2.1 as travis does not know about ruby_22 (and the CI build fails then ...)
> install pry-byebug to debug on 2.1 🌈

- lib/thor.rb
- spec/thor_spec.rb
Currently, doing so leads to
[~/dev/flat_fish]% autoproj test --help
Usage:
autoproj help [COMMAND]
instead of the expected result of "autoproj help test"
This case is handled internally by thor by transforming the subcommand invocation into `help *ARGV`
There were two problems:
- first invoke was called with (klass, args, options, parameters) while invoke expects (klass, subcommand, args, options, parameters)
- the --help argument was kept, which ends up as `help *ARGV --help, i.e. "give me the help of the 'help' subcommand
The commit removes the --help option before calling the subcommand, and fixes the call signature. It only does so for the "massaged" 'help' subcommand because invoke() has a way-too-weird call semantic for me to change the call in the general case without fearing to …
> fix 'thor_script subcommand [args] --help' 🌈 

- lib/thor.rb
- lib/thor/base.rb
- lib/thor/command.rb
- spec/register_spec.rb
- spec/subcommand_spec.rb
If these classes are defined,
```
module SubcommandTest1
class Child1 < Thor
desc "foo NAME", "Fooo"
def foo(name)
puts "#{name} was given"
end
end
class Parent < Thor
desc "child1", "child1 description"
subcommand "child1", Child1
end
end
```
`SubcommandTest1::Parent.start(%w[child1 foo])` puts messages to $stderr
on current master 
```
ERROR: "thor foo" was called with no arguments
Usage: "thor subcommand_test1:child1:foo NAME"
```
on this pull request branch
```
ERROR: "thor child1 foo" was called with no arguments
Usage: "thor child1 foo NAME"
```
> fix subcommand method help

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
- spec/fixtures/template/bad_config.yaml.tt
This seems to be all it takes to get the correct filename and line number to show up when there is an error in a .tt template.
Stacktrace before:
```
(erb):7:in `block in template': undefined method `each' for nil:NilClass (NoMethodError)
from (erb):5:in `each'
from (erb):5:in `template'
from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/2.1.0/erb.rb:850:in `eval'
from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/2.1.0/erb.rb:850:in `result'
from /opt/boxen/rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
```
Stacktrace after:
```
/Users/Thoughtworker/repos/opensource/swagger/swagger-thor/resources/templates/grape/files/app/api.rb.tt:7:in `block in template': undefined method `each' for nil:NilClass (NoMethodError)
from …
```
> Template stacktraces

- CHANGELOG.md
- lib/thor.rb
- lib/thor/base.rb
- lib/thor/command.rb
- lib/thor/parser/options.rb
- spec/thor_spec.rb
In Thor 0.19.2 it was added a new class method `disable_class_options`.
It was added to disable the check for required options in the help command. This new method disabled the option parser for help, so it is not possible to pass option to that command anymore.
That change introduced a regression and it is fixing the problem at the wrong level. What we want is to disable the required check not the option parsing.
So, we reverted the `disable_class_options` change and added a new method `disable_required_check!` to disable the required check in the commands we want.
Theoretically this is a breaking change but the `disable_class_options` introduction was also a breaking change so it is better to revert it and fix the problem at the correct place.
Related with #462 and #363.
See …
> Add disable_required_check! and make disable the check in help

- Gemfile
Simplecov(>= 0.12) has Fixnum waring in Ruby2.4.
I got warning by simplecov-0.12.0. 
```
$ bundle exec rspec spec
/Users/takkanm/src/github.com/erikhuda/thor/spec/helper.rb:31: warning: setting Encoding.default_external
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```
> update Simplecov dependency version

- spec/core_ext/ordered_hash_spec.rb
This PR refactors the `ordered_hash_spec` to keep with convention of the rest of the suite and added a few new specs.
There was a few issues i felt need addressing in this spec.
* wrap the described behaviour in `describe` blocks with the method name that is being tested.
* Don't use an instance variable as the test subject and don't depend on the state of the subject from previous specs
Thanks
> refactor ordered_hash_spec

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
🌈
If stdin is closed, any attempt to read user input returns `nil`, resulting in an infinite loop on file collision since that case isn't accounted for. The solution I have submitted treats `nil` the same as pressing enter. I'm also outputting a newline to prevent subsequent output from ending up on the same line.
> Prevent infinite loop on file collision when stdin closed

- lib/thor/actions.rb
- spec/actions_spec.rb
🌈 
This PR fixes a bug that I believe was introduced in 9dde9502be1730d59eafe2a2e8b3361cb11e3bb7 in `Thor::Actions#run`.
This is the current code:
```ruby
!options[:pretend] && config[:capture] ? `#{command}` : system(command.to_s)`.
```
As you can see, even if `options[:pretend]` is true, the command will be run.
I've reverted the change and added a test case.
> Fix commands running even with pretend enabled

- lib/thor/actions/empty_directory.rb
- spec/actions/create_file_spec.rb
In some cases creating a file would raise an exception, due to clashes with existing file. E.g. creating a file where a directory with the same name is present.
```
$ mkdir err
$ touch er/hello
$ irb
>> require 'thor'; class A < Thor; include Thor::Actions; end; a = A.new; a.create_file('./err/hello/boom')
create  err/hello/boom
Errno::EEXIST: File exists @ dir_s_mkdir - /Users/anodari/other_projects/thor/err/hello
from /Users/anodari/.rbenv/versions/2.4.0/lib/ruby/2.4.0/fileutils.rb:228:in `mkdir'
```
```
>> require './lib/thor'; class A < Thor; include Thor::Actions; end; a = A.new; a.create_file('./err/hello/boom')
file_clash  err/hello/boom
```
I would be more than happy to discuss further this issue. Feel free to comment about the naming and the approach.
> Fix "file clash" bug

- CHANGELOG.md
- lib/thor/base.rb
- lib/thor/parser/option.rb
- spec/helper.rb
- spec/parser/option_spec.rb
- spec/thor_spec.rb
It check if the default value of an option matches the defined type.
This removes the warning on usage since there is no much what the command users could do about it and give the command authors the possibility to check for programming errors.
> Add `check_default_type!`

- lib/thor/actions/inject_into_file.rb
- spec/actions/inject_into_file_spec.rb
When a file does not exists and sets `options[:pretend]`, it cause raise `Thor::Error`. So I've fixed it with minor refactoring.
> Fix bug and refactoring

- lib/thor/actions.rb
- lib/thor/actions/file_manipulation.rb
- lib/thor/base.rb
- lib/thor/command.rb
- lib/thor/group.rb
- lib/thor/parser/option.rb
- lib/thor/shell/basic.rb
- spec/actions_spec.rb
- spec/group_spec.rb
- spec/thor_spec.rb
These changes get Thor working when frozen string literals are enabled.
Regarding test suite dependencies and their compatibility with frozen string literals:
* RSpec is compatible in their latest git commits (for `rspec-core`, `rspec-expectations`, etc).
* `simplecov` and its dependency `simplecov-html` are compatible in their latest git commits.
* Addressable is compatible in this PR: https://github.com/sporkmonger/addressable/pull/260
* Webmock is not yet compatible - I'm working on it, though I've also uncovered a frozen string literal bug in stdlib. The patches I've made locally (not yet submitted to a PR) are enough to get Thor's build green though.
> Updates so things work with frozen string literals

- lib/thor/actions.rb
🌈
v0.20.0 [no longer requires OpenURI from `actions/file_manipulation.rb`](https://github.com/erikhuda/thor/compare/v0.19.4...v0.20.0#diff-a84da9a4ac4630ff251b04465cac2159L2).  This file is required by `actions.rb`. Since OpenURL is no longer loaded  a `no implicit conversion of Hash into String` error occurs when `Thor::Actions#apply` tries to load a file via HTTP(S) because `open` has not been modified [to accept HTTP headers](https://github.com/erikhuda/thor/blob/d55d8ad81f1739ed86c0a110af29d1582e51b7e4/lib/thor/actions.rb#L220):
```
/tmp/test-app-pad >padrino gen plugin coffee
apply  https://raw.github.com/padrino/padrino-recipes/master/plugins/coffee_plugin.rb
The template at https://raw.github.com/padrino/padrino-recipes/master/plugins/coffee_plugin.rb could not be found: no …
```
> require open-uri when loading http template

- Gemfile
Per https://github.com/liufengyun/hashdiff/issues/38 the hashdiff Gem no longer supports Ruby 1.8.  Locking the dependency to earlier versions to fix travis build.
> lock hashdiff to <0.3.6 to fix travis

- spec/actions/file_manipulation_spec.rb
This pull request addresses these failures reported #595 by duplicating string objects.
```ruby
$ ruby -v
ruby 2.6.0dev (2018-04-13 trunk 63143) [x86_64-linux]
$ bundle exec rspec ./spec/actions/file_manipulation_spec.rb
.. snip ..
................................
Failures:
1) Thor::Actions#get accepts http remote sources
Failure/Error: expect(content).to eq(body)
expected: ""
got: "__start__\nHTTPFILE\n__end__\n"
(compared using ==)
Diff:
@@ -1 +1,4 @@
+__start__
+HTTPFILE
+__end__
2) Thor::Actions#get accepts https remote sources
Failure/Error: expect(content).to eq(body)
expected: ""
got: "__start__\nHTTPSFILE\n__end__\n"
(compared using ==)
Diff:
@@ -1 +1,4 @@
+__start__
+HTTPSFILE
+__end__
Finished in 0.11101 seconds (files took 0.35057 seconds to load)
62 examples, 2 failures
Failed …
```
> Address #595 by duplicating string objects

- lib/thor/actions/file_manipulation.rb
The interface of `ERB.new` will change from Ruby 2.6.
> Add :trim_mode and :eoutvar keyword arguments to ERB.new.
> Now non-keyword arguments other than first one are softly deprecated
> and will be removed when Ruby 2.5 becomes EOL. [Feature #14256]
https://github.com/ruby/ruby/blob/2311087b685e8dc0f21f4a89875f25c22f5c39a9/NEWS#stdlib-updates-outstanding-ones-only
The following address is related Ruby's commit.
https://github.com/ruby/ruby/commit/cc777d0
This PR uses `ERB.version` to switch `ERB.new` interface. Because Thor supports multiple Ruby versions, it need to use the appropriate interface.
Using `ERB.version` instead of `RUBY_VERSON` is based on the following patch.
https://github.com/ruby/ruby/pull/1826
This patch is built into Ruby. …
> Deprecate safe_level of ERB.new in Ruby 2.6

- lib/thor/actions/file_manipulation.rb
Fix introduced in #594 misidentifies versions with more numerics.
As shown by @ahorek , version "2.11.0", for example, would be called using the deprecated API.
Long live ERB.
> Make sure future versions of ERB are invoked appropriately

- lib/thor/shell/basic.rb
This is a simple documentation update. I stumbled over the `default` option when I tried to create my own override for `ask` that included it.
> Updates method documentation for ask

- lib/thor/actions/file_manipulation.rb
🌈 
The previous regexp was likely a typo, and it prevented lines which begin with a pipe ("|") from being commented out.
> Fix comment_lines regexp

- lib/thor/shell/basic.rb
- spec/actions/create_file_spec.rb
- spec/shell/basic_spec.rb
Currently, if want to reflect the changed contents, only have to grasp the contents of diff and reflect it manually later or overwrite once to check the difference. This is a little inconvenient.
If merge is selected, the specified merge tool will be executed. By doing this, can reflect changes while checking.
The merge tool is obtained from environment variables and git config.
I doubt that it is appropriate to get a value from git config, but I am thinking that there may be useful.
> Add `merge` action to file colision menu

- spec/actions/file_manipulation_spec.rb
`inject_into_module` checks `module`, not `class`.
> Fix typo in `inject_into_module` test

- lib/thor/base.rb
- spec/fixtures/exit_status.thor
- spec/script_exit_status_spec.rb
🌈
Unlike the C library function exit(), Ruby's version takes a boolean,
not an integer. Added a spec to check the actual shell-level exit
value of a Thor script, and fixed calls to Process::exit.
> Fix incorrect use of Process::exit. This fixes open issue #244.

- README.md
In order to get a clean bill of health from ruby-audit, we should ensure any application developers are aware that they should not just take user input and pass it straight through to Thor.
Might render https://github.com/rubysec/ruby-advisory-db/pull/341 moot?
> Add language about how not to use Thor

- lib/thor/group.rb
- lib/thor/shell.rb
🌈 When using heredoc, the line number that is passed to `eval` method should be a `__LINE__ + 1`.
For example
```ruby
instance_eval <<-END, __FILE__, __LINE__
raise 'In the instance_eval'
END
```
It print below.
```bash
$ ruby test.rb
test.rb:1:in `<main>': In the instance_eval (RuntimeError)
from test.rb:1:in `instance_eval'
from test.rb:1:in `<main>'
```
It says "This exception occurred on the 1st line", but the `raise` is on the 2nd line.
This change will fix this problem.
> Use correct line numbers for `class_eval` and `module_eval` methods

- CHANGELOG.md
- lib/thor/parser/options.rb
- spec/thor_spec.rb
If the parsing gets stopped by either a `--` or by `#stop_on_unknown_option!`, then `check_unknown_options!` would still try to do validation on the unparsed parts.
This change now tracks where the stop happened and only check the `@extra` that were before that point.
For example, right now, `exec something -- --verbose` would fail because of `unknown switch --verbose` when `check_unknown_options!` is set.
> Fix check_unknown_options! when parsing gets stopped

- spec/parser/options_spec.rb
These three lines are misleading; the option `foo` is already created in the `before` block.
> Remove duplicate option creation in spec

- lib/thor/shell/basic.rb
- lib/thor/version.rb
:rainbow: Hi there!
While using Thor I found that the print_wrapped function behaves weirdly when manually inserting \x5 sequence (as per your docs) to force a line break. The original function doesn't takes those line breaks into consideration when calculating the length of the line, and the result is some extra weird line breaks on a long paragraph that includes such sequences (e.g. giving several execution examples).
I've rewrote this function, I reckon it's less "stylish", ~~and has a side effect that is unlikely a print_wrapped will use the whole terminal size~~, but it won't break intended multi-line paragraphs either.
Long story short, I'm breaking a paragraph in words, doing the "\x5" to "\n" replacement and keeping a counter that tells me when the line is over the terminal size, …
> Fix print_wrapped to properly parse "\x5" newline character

- Gemfile
- lib/thor/error.rb
`DidYouMean::SpellChecker` class added by `v1.0.2`.
https://github.com/yuki24/did_you_mean/blob/master/CHANGELOG.md#v102
Therefore, even if can use `did_you_mean`, may not be able to use
`DidYouMean::SpellChecker`. For that case, also ignored `NameError`.
> Add care about old version of `did_you_mean`

- lib/thor/error.rb
This caused a drastic performance hit (100x slower) on our JRuby applications because it was requiring `did_you_mean` even though we have:
```
JRUBY_OPTS="--disable:did_you_mean"
```
set. In looking through other libraries that use `did_you_mean`, it looks like a fairly common pattern is to just check if the portions of `did_you_mean` that are needed are defined. I tried to replicate that in this patch.
> Do not require did_you_mean

- lib/thor/parser/arguments.rb
`Object#=~` is deprecated in Ruby 2.6.
Ref: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?revision=65989&view=revision
> Fix "warning: deprecated Object#=~ is called on Integer"

- lib/thor/base.rb
- lib/thor/rake_compat.rb
This PR makes it so that we call `super` in various hook methods.
The default implementation of these methods (on Module) is just to no-op, so this ought to be safe to do.
This allows for other people to come along and add things to those hook methods (either before or after us), and as long as everyone supers up, all the hooks should get called as desired.
> Call super in hook methods

- lib/thor/runner.rb
🌈 
If an error is raised by `thor install` because of an invalid URI, the rescue block currently fails because it [references OpenURI](https://github.com/erikhuda/thor/blob/master/lib/thor/runner.rb#L62) and is not loaded. Update to load as needed.
reproduce with `bundle exec thor install foo`
> fix rescue of OpenURI

- spec/actions/inject_into_file_spec.rb
Hi,
when the testing system uses non-chinese charset (eg. `US-ASCII`), the test comes fail.
This patch will isolate the test from local system environment.
> Isolate the test from system charset environment

- lib/thor/base.rb
- lib/thor/shell.rb
This is a follow up to #668.
In bundler, I didn't want to rely on the LOAD_PATH for any internal requires because of the reasons given in #668.
But there's no `autoload_relative` in ruby, although there's a feature request: https://bugs.ruby-lang.org/issues/15330.
So my workaround was to instead require an absolute path, so that the LOAD_PATH is still not used.
> Use absolute paths for internal autoloads

- Gemfile
- lib/thor/actions/directory.rb
- spec/register_spec.rb
Just some additional cleanup motivated by dropping ruby 1.x support.
> Followup to ruby 1 support drop

- lib/thor/actions/file_manipulation.rb
This PR suppresses the follwoing warning in Ruby 2.7
```console
% ruby -v
ruby 2.7.0dev (2019-09-14T09:21:37Z master 39c37acf86) [x86_64-darwin17]
% bundle exec thor spec
(snip)
/Users/koic/src/github.com/erikhuda/thor/lib/ty
./Users/koic/src/github.com/erikhuda/thor/lib/thor/actions/file_manipulation.rb:89:
warning: calling URI.open via Kernel#open is deprecated, call URI.open directly
```
cf https://github.com/ruby/ruby/commit/05aac90a1bcfeb180f5e78ea8b00a4d1b04d5eed.
> Suppress `URI.open` warning in Ruby 2.7

- Gemfile
So we may use that consistently.
> pry-byebug supports all 2.x rubies

- lib/thor/parser/options.rb
- spec/parser/options_spec.rb
I was running  the command `bundle exec rails new --dev --skip-webpack-install my_project` inside my Rails clone, but Rails generators kept running `--skip-webpack-install`.
Turns out `thor` was considering `my_project` as the value for the `--skip-webpack-install` switch. However, I think the command line I specified is correct and non-ambiguous and that `--no-` and `--skip-` flags are not supposed to have a value.
This PR fixes this edge case.
It adds to tests, the first one is already passing against master, the second one is fixed by this PR. So, I think it also makes the behaviour more consistent.
Fixes #580.
> Fix `--skip-foo` switches when there's a trailing non-switch

- lib/thor/parser/options.rb
- spec/parser/options_spec.rb
The fix in bdb43eb unintentioanlly dropped support for specifying things like `--skip-foo=f` or `--skip-foo true`. In the first case, for no good reason, in the second, because "true" is now interpreted as a command option, not as a flag.
This PR restores support for those, so that arguments right after `--skip-foo` flags will never be interpreted as the flag's value, unless they are "true", "t", "false", or "f".
So
`my_program --skip-foo true`
means
"run my_program without arguments and the 'foo' flag unset".
whereas
`my_program --skip-foo asdf`
means
"run my_program with argument 'asdf' and the 'foo' flag unset".
By doing this, we still fix what #679 intended to fix, but still retain maximum backwards compatibility and flexibility.
> Amend `--skip-foo` fix with a trailing option

- lib/thor/shell/color.rb
- spec/shell/color_spec.rb
🌈 An informal standard for disabling color codes across the many command line tools that output terminal color codes has been described at [https://no-color.org](https://no-color.org)
Many of the tools that I already use have begun to support the variable, and having it in Thor would eventually allow most of the Ruby ecosystem tools I support to gain the functionality as well.
This PR scratches this itch by implementing NO_COLOR as [https://no-color.org](https://no-color.org) defines it:
> All command-line software which outputs text with ANSI color added should check for the presence of a NO_COLOR environment variable that, when present (regardless of its value), prevents the addition of ANSI color.
I'm unsure where the correct place to document this functionality might be. I grepped the …
> Respect the use of the NO_COLOR environment variable

- lib/thor/actions/inject_into_file.rb
- spec/actions/inject_into_file_spec.rb
> Fix TypeError when no config given and warn if file unchanged

- lib/thor.rb
- spec/fixtures/verbose.thor
- spec/no_warnings_spec.rb
In particular,
```
warning: global variable `$thor_runner' not initialized
```
Fixes #633.
> Fix uninitialized global variable warning

- lib/thor/line_editor/readline.rb
The current implementation of `readline` has issues under Windows, and those issues sometimes prevent `thor` from being used.
For example, in our bundler Windows CI, we had to patch `rb-readline` to workaround some issues
because `rb-readline` (the default `readline` provider on Windows) couldn't be required. Moreover, we still get some issues when requiring `rb-readline` like
```
HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory
```
Since in some situations the part of thor using `readline` (`Thor::LineEditor`) is not required, for example, in most of CI situations. I thought it could be a good idea to lazily require `readline`.
Just to be clear, this is not a problem with `thor` at all, but since requiring unnecessary things lazily is usually a …
> Lazily require `readline`

- lib/thor/line_editor/readline.rb
- spec/line_editor/readline_spec.rb
When dropping `1.8.7` support, I blindly removed this check, because the comment above it [suggested that it was 1.8.7-specific](https://github.com/erikhuda/thor/commit/ae4a3d50cd0d76a77aff80016171944958e0b22e#diff-bed9e34af04cfa7d71087d910326d750L16).
However, the check is also needed for `rb-readline`, the default readline implementation on modern rubies under Windows. See https://github.com/ConnorAtherton/rb-readline/blob/9fba246073f78831b7c7129c76cc07d8476a8892/lib/readline.rb#L91-L97.
So, I'm restoring the check, and the [specs changes](https://github.com/erikhuda/thor/commit/ae4a3d50cd0d76a77aff80016171944958e0b22e#diff-206c6f5b8b9cf96f472e3986abce7fbbL26-L33) that I included in the 1.8.7 support drop commit to get specs passing.
> Restore old check on `completion_proc=`

- lib/thor/actions.rb
- spec/actions_spec.rb
This option sets environmental variables for the executed command.
---
@deivid-rodriguez  Is this what you had in mind in https://github.com/rails/rails/pull/34980#discussion_r250640653?
> Add :env option to Actions#run

- lib/thor.rb
- lib/thor/base.rb
- spec/fixtures/command.thor
- spec/fixtures/script.thor
- spec/subcommand_spec.rb
- spec/thor_spec.rb
This forces implementers in defining `exit_on_failure?`, or else a deprecation warning is issued on error. See discussion in #621
> Deprecate relying on default exit_on_failure?

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
Hey all,
After using thor a bit, I thought it'd be useful to be able to match a limited_to option case-insensitively. I often use it for [y/n] prompts, but having the prompt list out all the possibilities [y, Y, n, N, yes, YES, no, NO], for instance, doesn't looks so great. Adding case-insensitive matching allows me to simplify that prompt to [y, yes, n, no].
After reading the contributing guidelines, I see you'd like documentation updated, though documentation doesn't appear to be in the repo, but in a wiki instead. Let me know if there's anything you'd like to see added to this PR to move forward with it.
Thanks!
> Add :case-insensitive flag to allow case-insensitive matching for :limited_to options 🌈

- lib/thor.rb
- lib/thor/base.rb
- lib/thor/parser/option.rb
- spec/thor_spec.rb
This issues a deprecation warning if one specifies an incompatible default value without either calling `allow_incompatible_default_type!` or passing `check_default_type: false`.
See discussion in #621
> Deprecate default check

- lib/thor/actions.rb
- lib/thor/base.rb
- spec/actions_spec.rb
Hi, there :rainbow:
I'd like to change the error handling of `Thor::Actions#run` for the following reason. 
According to the description of `exit_on_failure?`, the process should exit with status 1 if any error happens. I think that it should be also applied to `run`.
Although we can pass `abort_on_failure` option for `run`, passing it every time seems a little redundant when we call `run` multiple times. This is the other reason for this change.
For instance, when an error occres [here](https://github.com/rails/webpacker/blob/e95dd724ea3a385b9cc6935c3a07a34f1d1f9657/lib/install/elm.rb#L27), I want to notice not only by the output but also by the status code.
> Abort if the command for `run` fails and `exit_on_failure?` is true

- lib/thor/parser/arguments.rb
- spec/parser/arguments_spec.rb
For a number of tools, the argument `-` is often treated to mean STDIN. Currently, Thor is unable to accept `-` as an argument _value_, since it defines a flag as any entry beginning with `-`. This seems overly restrictive. I would argue that a flag is defined as follows:
>A flag is any entry that begins with 1 or 2 dashes, followed by _at least_ one character
In regex terms, this is `/-{1,2}\S+/`.
>  🌈 More accurate Arguments#current_is_value? check

- lib/thor/shell/html.rb
- lib/thor/util.rb
- spec/shell/html_spec.rb
This fixes issue addressed in https://github.com/erikhuda/thor/issues/440
> 🌈 Escapes HTML content when setting colors.

- lib/thor/actions.rb
It's not used anywhere, as far as I can see.
> Remove unnecessary "uri" require

- lib/thor/actions.rb
It's only used under very specific circumstances, so we can load it only when needed.
> Lazily load open3

- lib/thor/base.rb
- lib/thor/nested_context.rb
- spec/base_spec.rb
- spec/fixtures/script.thor
- spec/nested_context_spec.rb
In certain circumstances we may wish to nest `no_commands` blocks.
However, since when exiting the `no_commands` block the `@no_commands`
instance var is reset to `false`, we get unexpected behaviour.
For example, this will show warnings stating that the method `foo` is missing usage and a description:
```ruby
class Foo < Thor
no_method do
attr_reader :bar
def foo
'foo!'
end
end
end
```
This particular example is trivially solved but things get more difficult when, say, including modules.
```ruby
def no_commands
@no_commands = true
yield
ensure
@no_commands = false
end
```
This change uses a `NestedContext` object to track the depth of the `no_command` blocks and ensure that we only start creating commands again once we've left all of them.
- I'm definitely not sold on the name …
> Allow for nested no_commands blocks.

- lib/thor.rb
- lib/thor/base.rb
Make deprecation_warning available in Thor::Base and Thor::Option when
"thor" is not required, by moving it to "lib/thor/base.rb" which will
be required.
[Fixes #703]
> Move deprecation_warning to lib/thor/base.rb

- thor.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `source_code_uri`, and `wiki_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/thor), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- lib/thor/actions/create_link.rb
- spec/actions/create_link_spec.rb
🌈🌈🌈
The`create_link` action's documented behaviour is to interpret the `source` parameter as a relative path. While not explicitly stated, the implementation is that the source path is relative to the destination. However, `#identical?` treats the source path`render` as an absolute path when calling `File.identical?`.
Update `#identical?` to interpret the source path relative to the destination.
Alter `CreateLink` spec to allow variations in the source path to be tested, add spec testing `#identical?` for a relative source path.
You may or may not wish to accept the refactoring to the `CreateLink` spec. It felt like pulling the construction of the action apart like this was the cleanest way to allow this kind of variation between examples, but it is a broader change.
> Handle relative source path in create_link #identical?

- lib/thor/shell/color.rb
- spec/shell/color_spec.rb
🌈
It is possible for stdout to be a tty and still not support ANSI colors.  One example of this is the `:!` command in GVim or MacVim.  I had long assumed that the only way to reliably detect this was to introduce a heavyweight dependency such as libncurses, but recently I learned that checking that the environment variable `TERM` is set to a value other than `dumb` is largely sufficient.  This is what Git does, for example:
https://github.com/git/git/blob/0d0ac3826a3bbb9247e39e12623bbcfdd722f24c/editor.c#L11-L15
This patch implements identical behavior for Thor.
> Don't use ANSI colors when terminal is dumb

- lib/thor/shell/color.rb
- spec/shell/color_spec.rb
🌈
When I added this behavior, I wasn't taking Windows into account.  My inspiration Git handles it by [defaulting `TERM` on Windows](https://github.com/git/git/blob/0d0ac3826a3bbb9247e39e12623bbcfdd722f24c/compat/mingw.c#L2414-L2416), but Ruby has no such equivalent.  I don't think `TERM` will ever be missing on UNIX under normal tty circumstances, so I think it's safe to drop the guard on all platforms.
Thanks for your patience!
> Restore colors when TERM is unset

- lib/thor/parser/arguments.rb
- spec/parser/options_spec.rb
Following work on https://github.com/Shopify/krane/issues/697, I discovered a subtle bug that is now causing issues with the [repeatable flag feature](https://github.com/erikhuda/thor/pull/674).
If a default argument for a `Thor::Option | Thor::Argument` is provided, the option/argument constructor will call:
```
@assigns[argument.human_name] = argument.default
```
This aliases, __and does not create a copy of__, `argument.default` to `@assigns[argument.human_name]`. So now every time we update `@assigns`, we are also mutating `argument.default`. This was never a problem before because, without a repeatable flag, we'd never encounter a failure mode.
> 🌈 Need to dup default or else we have a troublesome alias

- Gemfile
Commit 693c2e91 introduced a dependency on `to_stderr_from_any_process`,
an API introduced in rspec 3.2.
> 🌈 Update required rspec version

- lib/thor/line_editor/readline.rb
- spec/line_editor/readline_spec.rb
An error was introduced in commit 7061b06fd87dc8b952f9072507ee991ee0a0858e
where readline specs fail because `require "readline"` is called after the
spec has established a mock `::Readline`. Prior to that change
`require "readline"` was always only called once.
This patch:
* memoizes the `require` to ensure that it only happens once
* leaves the `Object.const_defined?` check in place to keep tests simple
* eagerly calls `available?` in the readline spec to match the original
author's intent by requiring `readline` before the specs start.
This error wasn't caught by CI due to the bundler cache. You can see the failure caused by the earlier change by [removing the Bundler cache from Travis](https://travis-ci.org/bpo/thor/jobs/658865414)
> 🌈 Fix readline specs

- lib/thor.rb
- spec/fixtures/verbose.thor
- spec/no_warnings_spec.rb
Last patch for me today - this was what I was originally trying to do:
Previously `ruby -w`, when running an unknown command in Thor, a warning was
printed:
thor-1.0.1/lib/thor/base.rb:514: warning: global variable `$thor_runner' not initialized
This was raised earlier in #633 but the fix was incomplete -- the global variable was being lazily defined in a method which is not the only entry point to Thor. This moves the global definition out to where the Thor class is defined.
> 🌈 Fix another warning about $thor_runner

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
This pull request fixes a bug that caused the `print_wrapped` method in the `Thor::Shell::Basic` class to incorrectly wrap the text when printing on the terminal. The reason for the bug is that the method assumes that the loop starts with the first word, when in fact it starts with the second word and the first word is already in the `memo` variable.
To see why this occurs you can run the following code on IRB or PRY:
```
>%w[hello world! how are you doing].inject { |memo, word| puts "#{memo} : #{word}"  }
hello : world!
: how
: are
: you
: doing
=> nil
```
As you can see the first iteration already has `"hello"` in `memo` and the first `word` is actually `"word!"`. The `print_wrapped` was not accounting for this and therefore given the right conditions the method would print beyond the …
> 🌈 Fixes a bug in the calculation of the print_wrapped method

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
`Shell#say_status` already obeys `mute` and `options[:quiet]`.  This commit makes `Shell#say` obey them as well.
> Obey mute and options[:quiet] in Shell#say

- lib/thor.rb
Set has been gemified as of ruby 3.0.0. Since `bundler` vendors `thor` internally, it's helpful for `bundler` that `thor` doesn't use `set`, so that `bundler` doesn't activate the gem `set` too early and final users can still specify whichever version of `set` they want in their Gemfiles.
> 🌈 Replace `set` usages with arrays

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
This allows for running gsub_file regardless of whether running in invoke or revoke mode
> Add force option to the gsub_file action

- lib/thor/core_ext/hash_with_indifferent_access.rb
- spec/core_ext/hash_with_indifferent_access_spec.rb
This PR supports `Thor::CoreExt::HashWithIndifferentAccess#except` and prevents breaking changes in Rails upgrades when using `options.except(:key)` in Thor task.
When Thor is used with Rails (Active Support), the behavior changes as follows.
```ruby
h = Thor::CoreExt::HashWithIndifferentAccess.new(foo: 1, bar: 2)
h.except(:foo) #=> {"bar"=>2}
```
```ruby
h = Thor::CoreExt::HashWithIndifferentAccess.new(foo: 1, bar: 2)
h.except(:foo) #=> {"foo"=>1, "bar"=>2}
```
This difference behavior is due to the following changes in Rails 6.0.
https://github.com/rails/rails/pull/35771
This PR makes the behavior between Rails 5.2 and Rails 6.0 compatible.
> Support `Thor::CoreExt::HashWithIndifferentAccess#except` for Rails 6.0

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
I think that in most cases the target klass is not defined in a file that uses inject_into_class.
So it is more friendly to set the default comment to string type.
as-is
```
inject_into_class "xxx.rb", ApplicationController, "Lorem"
```
to-be
```
inject_into_class "xxx.rb", "ApplicationController", "Lorem"
```
I think it's more realistic for test specs to delete the empty class definition in the first line.
Also about the inject_into_module.
> 🌈The klass parameter 'inject_into_class' should be given a string type.(also inject_into_module)

- lib/thor/shell.rb
- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
* Like `#say` but prints to `stderr`.
* Allows for printing ANSI colored error messages to `stderr`.
> Added Shell::Basic#say_error

- lib/thor/actions/inject_into_file.rb
- spec/actions/inject_into_file_spec.rb
I ran into some unexpected behavior today with `insert_into_file`. I was trying to insert `, null: false` into a migration after some text, but nothing happened. 
```ruby
t.belongs_to :recipient, null: false
t.string :type
````
```ruby
insert_into_file path, ", null: false", after: "t.string :type"
```
This does nothing because `, null: false` exists in the file (anywhere).
Using `after:` I would expect `insert_into_file` to only care if the string exists _after_ the matching line, not before it.
This PR would change the behavior to only look through the before or after portions of the file content to make it more intuitive.
> Check for duplicate content in relevant section when inserting into files

- lib/thor/util.rb
- spec/util_spec.rb
This PR is to fix the directory that thor goes to look for
When an arbitrary directory is created under the tasks directory, the thor files in that directory will also be read.
> Loaded the directory under tasks.

- lib/thor/actions.rb
- spec/actions_spec.rb
🌈
So that calling code can more conveniently inspect & use this value.
The value previously returned by this method doesn't seem useful so this seems like a safe change to make.
If this looks OK, should I also update the CHANGELOG?
> 🌈 Update `Thor::Actions#inside` to return the value yielded by the block

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
The problem is that `remove_file` only checks if `File.exist?` which is false if the symlink target does not exist (anymore). In [`create_link`](https://github.com/erikhuda/thor/blob/34df888d721ecaa8cf0cea97d51dc6c388002742/lib/thor/actions/create_link.rb#L56) this was already considered.
> `remove_file` should unlink broken symlinks

- spec/shell/basic_spec.rb
Code editors are commonly configured to strip trailing whitespace when saving.  Additionally, trailing whitespace may be hard to distinguish visually, both in the editor and in diffs.
This commit uses string interpolation to encode expected trailing whitespace.
> Use string interpolation for trailing whitespace

- lib/thor/shell/basic.rb
- spec/shell/basic_spec.rb
This prevents multiline status messages from breaking the left margin.
As an example, before this commit:
```
status1  single line
status2  multiline line 1
multiline line 2
multiline line 3
status3  multiline indent 0
multiline indent 2
multiline indent 4
status4  single line
```
And after this commit:
```
status1  single line
status2  multiline line 1
multiline line 2
multiline line 3
status3  multiline indent 0
multiline indent 2
multiline indent 4
status4  single line
```
Closes rails/rails#38387.
> Indent multiline messages in say_status

- lib/thor/parser/options.rb
- spec/parser/options_spec.rb
This is a fixed version of #498.
This allows `--foo=-bar` to work.
The implementation works by keeping track of an additional piece of state `@force_current_to_be_value`, which is maintained inside `shift` and `unshift` to ensure it matches the state in `@pile`.
> Allow leading hyphen in switch values when specified with =

- README.md
- thor.gemspec
This PR replaces erikhuda/thor with rails/thor. It will clarify the repository location and reduce redundant http redirects.
> Replace erikhuda/thor with rails/thor

- lib/thor/error.rb
Using `DidYouMean::SPELL_CHECKERS.merge!` has been deprecated.
Since this new version will be included with Ruby 3.1, I'm looking into supporting it without warnings.
> Support latest did_you_mean

- .github/workflows/tests.yml
Due to actions/runner#849, we have to use quotes for 3.0.
Currently CI runs against latest 3 series, 3.1.
> Fix CI setting for Ruby 3.0

- Gemfile
- spec/helper.rb
- spec/line_editor_spec.rb
- spec/parser/options_spec.rb
- spec/shell/basic_spec.rb
🌈  This is a combination of #777, #778, #779 if you prefer a single green PR 😀
> Fix CI to be green

- .github/workflows/lint.yml
- .gitignore
- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- lib/thor.rb
- lib/thor/base.rb
- lib/thor/group.rb
- lib/thor/parser/arguments.rb
- lib/thor/parser/option.rb
- lib/thor/parser/options.rb
- lib/thor/rake_compat.rb
- lib/thor/runner.rb
- lib/thor/shell/basic.rb
- lib/thor/util.rb
- lint_gems.rb
- spec/actions/file_manipulation_spec.rb
- spec/shell/basic_spec.rb
I noticed that even if the code includes RuboCop inline comments disabling cops, RuboCop is (no longer?) run in CI.
This PR upgrades RuboCop, fixes configuration and issues, and runs it in CI.
It does not change any styles that were not previously configured.
> Upgrade RuboCop, fix config and offenses, and run it in CI

- lib/thor/runner.rb
- spec/runner_spec.rb
On FIPS-compliant systems (http://en.wikipedia.org/wiki/FIPS_140), MD5
cannot be used. Switch to SHA256 instead.
However, this change does not keep backward compatibility with systems
with already-installed Thor recipes.
Closes #287
> Switch hash from MD5 to SHA256

- Gemfile
- lib/thor/shell/color.rb
- spec/shell/color_spec.rb
Since implementation the NO_COLOR specification has changed. Previously
if NO_COLOR was set in the environment it should be respected regardless
of value. In the new updated specification NO_COLOR should only be
respected if set to any non-empty string.
See this comment thread on the original commit for more information.
https://github.com/rails/thor/commit/21e65684432c0fcc975c1d6fda497da24149f763#r80414525
Fixes #795
> Respect the updated NO_COLOR specification

- .github/workflows/tests.yml
- Gemfile
This patch adds CI configuration for Ruby 3.2.
Also, I noticed that the CI matrix includes Ruby `2.0` that would be parsed as integer `2` in GH actions. This means that Ruby 2.0 has never been tested on GH actions. I fixed this to be quoted `'2.0'`, and brought Ruby 2.0 testing back.
> CI against Ruby 3.2 (and 2.0)

- lib/thor/shell/basic.rb
- Support for HP-UX was dropped in ruby/ruby#5457.
- The IRIX OS is no longer maintained with the last release being 16 years ago.
> Remove support for deprecated OS

- lib/thor/base.rb
It makes it hard to locate code when profiling etc.
> Avoid anonymous eval

- lib/thor/runner.rb
- spec/runner_spec.rb
The previous code suggested that this was supported, but it was not really working as expected.
> Support `thor install <uri>` to install remote thor files

- lib/thor/actions.rb
- lib/thor/actions/file_manipulation.rb
- lib/thor/runner.rb
- spec/actions_spec.rb
👋  CodeQL detects "Use of `Kernel.open` or `IO.read` with a non-constant value" warnings in https://github.com/ruby/ruby. I hope to suppress them.
> Prefer to use URI.open and File.open instead of Kernel.open

- lib/thor/actions/inject_into_file.rb
🌈 The `replace! ` method fails if the flag is not found OR if the text is already present.  The error message only says that the flag has not been found.   This is incorrect/misleading in the case where it has actually failed because the content is already present.  This is pr just adds that to the error message.
Alternatively, could add a separate error message, change the return value from `replace!` to indicate the type of error but this seems like overkill.
> Update error message for content already exists case.

- lib/thor/actions/create_file.rb
- spec/actions/create_file_spec.rb
Ref rails/rails#48135
Previously, to restrict the permissions of a file created using create_file, chmod could be called right after. However, that leaves a short amount of time between when the file is first created and when the permissions are updated where another user could read the file.
This commit enables passing file permissions to create_file so that permissions can be set when the file is created.
> Allow setting file permissions with create_file

- lib/thor/base.rb
- lib/thor/parser/option.rb
- spec/base_spec.rb
When printing the options of a command, options without aliases are
padded so they align with options with aliases
The size of the padding is calculated by multiplying the max number of aliases
for an option by the number 4 (a dash, a letter, a comma and a space?).
Options can have aliases of arbitrary length, not just just a dash with
a single letter. For example in Rails the `main` option has the [alias](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/app_base.rb#L100)` --master`.
Also, the current implementation adds padding only to options without aliases.
So if one options has 1 alias and another has 2 aliases, the first option won't
get padding.
This all results in strange output when callings `bin/rails new -h`:
```console
-T, [--skip-test], [--no-skip-test] …
```
> Properly pad aliases for option usage

- lib/thor/util.rb
- spec/base_spec.rb
- spec/fixtures/script.thor
- spec/util_spec.rb
check commands to find the correct class when multiple classes have the same namespace
this is related to https://github.com/rails/thor/issues/246 and https://github.com/rails/thor/pull/247
I'm assuming the intention was to allow multiple classes to use the same namespace. I guess I don't understand the reasoning for the namespace if it can only be used for a single class.
🌈
> use the correct class for shared namespaces

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
🌈
Sometimes we want to use `get` to make requests to an API or endpoint that requires certain headers to be present (such as auth).
[OpenURI](https://ruby-doc.org/stdlib-3.1.2/libdoc/open-uri/rdoc/OpenURI.html) supports providing headers for the request, we just need to have a way of providing them.
This PR adds `:http_headers` as a config option to `get`, and is essentially just passed directly to `URI.open`.
Hopefully the test coverage and documentation is sufficient.
❤️💜💚💙💛
> Add support for providing http headers to get

- lib/thor/actions/create_file.rb
- spec/actions/create_file_spec.rb
🌈
Currently if you regenerate a file that contains a multi-byte UTF-8 codepoint (such as €) the file will falsely be identified as having changed. This PR adds a test to the create_file_spec to identify the problem, and then fixes the problem.
The change is the same as in https://github.com/rails/thor/pull/656, but that PR seems to have languished unmerged for just over 3yrs. I'm hoping the testing approach in the PR will address the previous objections so that the change can be merged.
> CreateFile#identical? fixed for files containing multi-byte UTF-8 codepoints

- lib/thor/parser/option.rb
- lib/thor/parser/options.rb
- spec/parser/option_spec.rb
🌈
When option aliases are specified without dashes
```ruby
option :from, aliases: [:f]
```
they are correctly handled when parsing the command
```
my_cli hello -f Loki Thor
from: Loki
Hello Thor
```
However the usage information does not include the dash. This PR fixes that by moving alias normalization to happen sooner, so it applies to both the usage information generator and the actual command:
```diff
my_cli help hello  
Usage:
my_cli hello NAME
Options:
-  f, [--from=FROM]  
+  -f, [--from=FROM]  
say hello to NAME
```
> Fix dashless option usage info

- lib/thor/base.rb
- lib/thor/parser/argument.rb
- lib/thor/parser/arguments.rb
- spec/parser/argument_spec.rb
- spec/parser/options_spec.rb
Adds support for additional enumerable types in `:enum` options.
> Support Range in enum option

- lib/thor/actions/inject_into_file.rb
- spec/actions/inject_into_file_spec.rb
Not sure if the fix implementation is good enough. Let me know if you want some changes.
Closes #706.
> Fix inject into file warning

- lib/thor/core_ext/hash_with_indifferent_access.rb
- spec/core_ext/hash_with_indifferent_access_spec.rb
resolve https://github.com/rails/thor/issues/804
This PR supports `Thor::CoreExt::HashWithIndifferentAccess#slice`.
```ruby
hash = Thor::CoreExt::HashWithIndifferentAccess.new 'foo' => 'bar', 'baz' => "bee"
hash.slice('foo')
hash.slice(:foo)
```
Thank you. 🌈
> Support `Thor::CoreExt::HashWithIndifferentAccess#slice` method

- lib/thor.rb
- lib/thor/command.rb
- spec/command_spec.rb
- spec/fixtures/script.thor
- spec/thor_spec.rb
The PR implements [this suggestion](https://github.com/erikhuda/thor/issues/398#issuecomment-364503506) from the #398 comments. `long_desc` now receives a new option `wrap`. Setting it to `false` disables wrapping of the long description and prints it verbatim.
```ruby
long_desc <<~MSG, wrap: false
formatted text that is not wrapped
...
MSG
```
It adds a new obligatory constructor argument to `Thor::Command`. If the constructor is considered part of the public API, this may be a problem.
*(I did read CONTRIBUTING.md, but I prefer not to use the rainbow emoji because of the meanings it usually carries nowadays, hence the cloud in PR title.)*
> 🌧️ long_desc: new option to disable wrapping

- lib/thor/parser/option.rb
- spec/parser/option_spec.rb
🌈 I just learned, that there is an open issue #819 already, which will be solved by this PR.
> Print default in help when option type is :boolean and default is false

- lib/thor.rb
- lib/thor/base.rb
- spec/thor_spec.rb
`method_option` and `class_option` require a String or Symbol as the first argument.
This can be somewhat confusing when `method_options` and `class_options` require a Hash as argument.
Fixes #808
> Validate arguments for `method_option` and `class_option`

- lib/thor/shell/basic.rb
Fix https://github.com/rails/thor/issues/818
Branch help for file_collision depending on block_given.
This will change the order of the help slightly, but probably not a problem.
When I ran the sample code described in the issue(#818), it looked like this:
```shell
$ ruby ./thor.rb hello
=== file_collision with no block
Overwrite ./foo.txt? (enter "h" for help) [Ynaqh] h
Y - yes, overwrite
n - no, do not overwrite
a - all, overwrite this and all others
q - quit, abort
h - help, show this help
Overwrite ./foo.txt? (enter "h" for help) [Ynaqh] y
=== file_collision with block
Overwrite ./foo.txt? (enter "h" for help) [Ynaqdhm] h
Y - yes, overwrite
n - no, do not overwrite
a - all, overwrite this and all others
q - quit, abort
h - help, show this help
d - diff, show the differences between …
```
> Fix help for file_collision method without block

- lib/thor/shell/basic.rb
- lib/thor/shell/column_printer.rb
- lib/thor/shell/table_printer.rb
- lib/thor/shell/terminal.rb
- lib/thor/shell/wrapped_printer.rb
- spec/shell/basic_spec.rb
- spec/thor_spec.rb
The printing methods are already pretty large, making it difficult to add extra functionality. Extracting them to seperate classes allows refactoring them for easier maintainability.
A lot of the functionality of calculating the terminal width can be extracted to a separate object as well.
> Extract print methods to seperate classes

- lib/thor/shell/basic.rb
- lib/thor/shell/table_printer.rb
- spec/shell/basic_spec.rb
Adding borders to tables can improve their legibility.
_Before_
```
Name  Number  Color
Erik       1  green
Ruby       2  red 
```
_After with `borders: true`_
```
+------+--------+-------+
| Name | Number | Color |
+------+--------+-------+
| Erik |      1 | green |
| Ruby |      2 | red   |
+------+--------+-------+
```
This would allow replacing the [custom table](https://github.com/rails/rails/blob/4e01a7e8753c30e22264e185082524a9ea5e0c90/railties/lib/rails/code_statistics.rb#L81-L116) for code statistics in
Rails, with the generic implementation in Thor.
By adding :separators to a table a horizontal separator will be added.
This functionality was inspired by: https://github.com/piotrmurach/tty-table
Having the ability to add separators where required adds more flexibility instead of …
> Add support for printing tables with borders

- lib/thor/shell/table_printer.rb
- spec/shell/basic_spec.rb
When printing tables with borders and indentation the resulting markup was incorrect.
Instead of adding the indentation to the format of the first cell, with indent the whole line.
Before:
```
+------  +--------  +-------+
|   Name | Number | Color |
|   Erik |      1 | green |
+------  +--------  +-------+
```
After
```
+------+--------+-------+
| Name | Number | Color |
| Erik |      1 | green |
+------+--------+-------+
```
> Fix printing tables with borders and indentation

- lib/thor/shell/table_printer.rb
As Thor requires Ruby >= 2.6 we don't need to check if String responds to `#encode`, as this is supported since Ruby 1.9.2 at least: https://www.rubydoc.info/stdlib/core/1.9.2/String:encode
> Remove String#encode conditional required by Ruby < 2.6

- .github/workflows/tests.yml
when thor 1.3.0 is vendorized, lcs_diff.rb emits method redefinition warnings as follows:
> .../src/github.com/rails/thor/lib/thor/shell/lcs_diff.rb:6: warning: method redefined; discarding old show_diff
> .../.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/shell/lcs_diff.rb:6: warning: previous definition of show_diff was here
> .../src/github.com/rails/thor/lib/thor/shell/lcs_diff.rb:21: warning: method redefined; discarding old output_diff_line
> .../.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/shell/lcs_diff.rb:21: warning: previous definition of output_diff_line was here
> .../src/github.com/rails/thor/lib/thor/shell/lcs_diff.rb:37: warning: method redefined; discarding old …
> Avoid loading bundler 2.4.22 that vendorizes thor 1.3.0

- .github/workflows/lint.yml
- .github/workflows/tests.yml
GitHub is [planning to upgrade to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Versions prior to actions/checkout v3 use an outdated version of node, so we will upgrade to actions/checkout v4, where [Node 20 is the default](https://github.com/actions/checkout/releases/tag/v4.0.0).
> Bump actions/checkout

- lib/thor/shell/basic.rb
- lib/thor/shell/html.rb
that put the balise `<code>` inside the generated documentation
source: https://www.rubydoc.info/github/wycats/thor/Thor/Shell/Basic:ask
ps : i change "Pluto" by "Neptune" because [Pluto is not a planet anymore](https://loc.gov/rr/scitech//mysteries/pluto.html#:~:text=In%20August%202006%20the%20International,will%20be%20designated%20as%20planets.)
> Improve the code documentation with indentation

- lib/thor/actions/file_manipulation.rb
Currently, the documentation of action `copy_file` is slightly broken because of an unnecessary blank line.
Details: https://www.rubydoc.info/gems/thor/Thor/Actions
This PR removed the blank line to fix the documentation.
> Fix documentation of action `copy_file`

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
- spec/fixtures/doc/COMMENTER
🌈
When using Thor's `uncomment_lines` method to programmatically uncomment lines in YAML files or similar, the method was found to inaccurately handle the preservation of indentation spaces before the comment hash (`#`). Particularly, when uncommenting lines in structured files where indentation is crucial (like YAML files), the original method removed not only the comment hash but also all horizontal whitespace between the hash and the beginning of the content. This behavior led to a disruption in the file's structure and could potentially cause errors when the file was processed or parsed afterward.
For example, in a `.github/workflows/ci.yml` file containing commented-out configuration for Redis:
```yml
```
Applying `uncomment_lines` with the previous implementation would result in …
> Preserve Correct Indentation When Uncommenting Lines

- lib/thor/parser/option.rb
- lib/thor/parser/options.rb
- spec/parser/option_spec.rb
When specifying a boolean option `foo`, Thor will accept `--skip-foo` as an options (the same as `--no-foo`). This behaviour was previously undocumented.
This PR updates the documentation in the repo and also the `usage` method to make this feature more discoverable.
> Document the '--skip-' option for boolean options.

- lib/thor.rb
- lib/thor/group.rb
- lib/thor/util.rb
- spec/fixtures/script.thor
- spec/group_spec.rb
- spec/thor_spec.rb
- spec/util_spec.rb
Fixes https://github.com/rails/thor/issues/868
Problem:
After version 1.3.0, invoking commands with hyphenated and alias names does not function as expected.
Given a Thor class definition as follows:
```
class Test < Thor
desc "foo-bar", "an example task"
def foo_bar
puts "I'm a thor task!"
end
map "fb" => :foo_bar 
end
```
Each command results in the following.
```
% thor test:foo_bar
I'm a thor task!
```
```
% thor test:foo-bar
Commands:
thor test:foo-bar         # an example task
thor test:help [COMMAND]  # Describe available commands or one specific command
```
```
% thor test:fb
Commands:
thor test:foo-bar         # an example task
thor test:help [COMMAND]  # Describe available commands or one specific command
```
This PR addresses the issue by implementing a fix in the …
> Correctly identify hyphenated and alias command names

- spec/thor_spec.rb
This commit addresses the following failures against Ruby 3.4.0dev that includes https://github.com/ruby/ruby/pull/10924 . This commit also passes specs againt Ruby 3.3.5.
```ruby
$ ruby -v
ruby 3.4.0dev (2024-10-26T13:20:34Z master 484ea00d2e) +PRISM [x86_64-linux]
$ bundle exec rspec ./spec/thor_spec.rb
Source locally installed gems is ignoring #<Bundler::StubSpecification name=prism version=1.0.0 platform=ruby> because it is missing extensions
Source locally installed gems is ignoring #<Bundler::StubSpecification name=json version=2.7.2 platform=ruby> because it is missing extensions
Source locally installed gems is ignoring #<Bundler::StubSpecification name=google-protobuf version=4.27.0 platform=ruby> because it is missing extensions
Source locally installed gems is ignoring …
```
> Support Ruby 3.4 `Hash#inspect` change

- spec/base_spec.rb
- spec/parser/options_spec.rb
This commit addresses the following warnings.
- Steps to reproduce:
```ruby
$ ruby -v
ruby 3.4.0dev (2024-10-26T13:20:34Z master 484ea00d2e) +PRISM [x86_64-linux]
$ RUBYOPT="--debug-frozen-string-literal" bundle exec thor spec
```
- Warnings addressed by this commit:
```
/path/to/thor/spec/base_spec.rb:322: warning: literal string will be frozen in the future
/path/to/thor/spec/base_spec.rb:321: info: the string was created here
```
```
/path/to/thor/spec/parser/options_spec.rb:121: warning: literal string will be frozen in the future
/path/to/thor/spec/parser/options_spec.rb:120: info: the string was created here
```
Refer to:
https://bugs.ruby-lang.org/issues/20205
https://github.com/ruby/ruby/pull/11893
> Address `warning: literal string will be frozen in the future`

- .github/workflows/tests.yml
- Gemfile
This pull request adds Ruby 3.4 to CI matrix.
> Add Ruby 3.4 to CI matrix

- lib/thor/runner.rb
This avoids errors when Bundler is activated _after_ thor, and a different version of YAML (or dependencies of it, like stringio) is included in the Gemfile/Gemfile.lock than the one that thor activates internally.
> Lazily load YAML

- lib/thor/shell/basic.rb
- spec/actions/create_file_spec.rb
- spec/shell/basic_spec.rb
Requested at from [GHSA-9497-wr55-jwhj](https://github.com/rubygems/rubygems/security/advisories/GHSA-9497-wr55-jwhj)
Dynamically constructing a shell command with inputs from exported functions may inadvertently change the meaning of the shell command. Clients using the exported function may use inputs containing characters that the shell interprets in a special way, for instance quotes and spaces. This can result in the shell command misbehaving, or even allowing a malicious user to execute arbitrary commands on the system.
> fix: Unsafe shell command constructed from library input

- lib/thor/actions/file_manipulation.rb
- spec/actions/file_manipulation_spec.rb
🌈
---
This is a straw-person solution for #874  - overall I think it's not bad but expect changes to be requested; in particular, the option name is pretty verbose so happy if someone wants to suggest an alternative though to me really its about having `gsub_file!`.
A bonus to this is that anything using `gsub_file` also supports this behaviour such as `comment_lines` and `uncomment_lines` - I think it would be nice to have bang versions of such methods too but want to get the core behaviour/implementation nailed down first.
Resolves #874
> feat: support `gsub_file` erroring if gsub doesn't change anything, and add `gsub_file!`

- lib/thor/parser/options.rb
I spotted a typo while reading a comment in the source code 👀
> Correct typo in comment

- CONTRIBUTING.md
Add some simple guidance on running specs and linters. 🌈
> Add specs and linter documentation

- lib/thor.rb
- spec/fixtures/script.thor
- spec/thor_spec.rb
If a command is hidden from help, I think it should not be considered when checking if an invocation is ambiguous.
> Hidden commands should not make an invocation ambiguous

- lib/thor/shell/color.rb
We should use frozen string literals in this file. There are a bunch of string literals in constants that should be constant.
> Set frozen_string_literal: true in colors.rb
